### ISSUE TITLE
Unique Identifier missing

### ISSUE THREAD

**Issue by 4handheld** [KryptoKnight/a45623#4]
The data from the api does not include a unique identifier for each user, ie a unique integer ID. What should I use in this case?

**Comment by baole** [comment]
As the UI doesn't need/show a unique identifier, and we suppose that the API returns unique members, it's up to you to decide.

**Comment by 4handheld** [comment]
Ok

**Comment by 4handheld** [comment]
I need the identifier to map the like button to each unique user
